; ---------------------------------------------------------------------------------------------------------------------------------
; To change the videos, simple change the filename from the "INTRO" folder.
; The Smacker Video extension (*.smk) can be omitted; the game appends it automatically.
; If you do not want a video to be played, just delete the path.
; ---------------------------------------------------------------------------------------------------------------------------------

[INTRO]
; If you set this to TRUE, all the default JA2 videos will be disabled (not shown to the user).
NO_DEFAULT_VALUES = FALSE

[INTRO_BEGINNING]
INTRO_HELI_CRASH_SCENE = INTRO\\Intro

[INTRO_ENDING]
INTRO_END_SCENE = INTRO\\MissileEnding
